branches:
  only:
    - master
before_script: cp config/database.yml.example config/database.yml
language: ruby
matrix:
  allow_failures:
    - rvm: 2.0.0
rvm:
  - 1.9.3
  - 2.0.0
script: bundle exec rake db:create db:migrate db:test:prepare default
