before_install:
  - gem update --system 1.8.25
before_script:
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:create db:migrate db:test:prepare
git:
  strategy: tarball
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: 2.1.1
script: bundle exec rake default
services:
  - redis-server
