before_script:
  - rvm rubygems 1.8.25
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:create db:migrate db:test:prepare
language: ruby
rvm:
  - 1.9.3
script: bundle exec rake default
